- project:
    check:
      jobs:
        - "thoth-coala"
    gate:
      jobs:
        - "thoth-coala"
    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "osiris-api"
    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
