apiVersion: v1
kind: Template
metadata:
  name: osiris-api-configmap
  annotations:
    description: >
      This is Osiris API ConfigMap Template.
    openshift.io/display-name: 'Thoth: Osiris API - ConfigMap'
    version: 0.1.0
    tags: build,build-aggregator,build-analysis,thoth,osiris,osiris-api
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris API ConfigMap Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-configmap
    app: osiris

parameters:
  - description: Ceph storage identification
    displayName: Ceph key
    required: true
    name: CEPH_KEY_ID

  - description: Ceph storage secret key
    displayName: Ceph secret key
    required: true
    name: CEPH_SECRET_KEY

objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      labels:
        app: osiris
        component: configmap
      name: osiris
    data:
      OSIRIS_HOST_PORT: '8000'
      THOTH_CEPH_BUCKET: DH-DEV-DATA
      THOTH_CEPH_BUCKET_PREFIX: data/thoth
      THOTH_CEPH_KEY_ID: ${CEPH_KEY_ID}
      THOTH_CEPH_SECRET_KEY: ${CEPH_SECRET_KEY}
      THOTH_DEPLOYMENT_NAME: thoth-osiris
      THOTH_S3_ENDPOINT_URL: https://s3.upshift.redhat.com
