apiVersion: v1
kind: Template
metadata:
  name: osiris-api-configmap
  annotations:
    description: >
      This is Osiris API ConfigMap Template.
    openshift.io/display-name: 'Thoth: Osiris API - ConfigMap'
    version: 0.1.0
    tags: build,build-aggregator,build-analysis,thoth,osiris,osiris-api
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris API ConfigMap Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-configmap
    app: thoth
    component: osiris-api

parameters:
  - description: Ceph storage identification
    displayName: Ceph key
    required: true
    name: CEPH_KEY_ID

  - description: Ceph storage secret key
    displayName: Ceph secret key
    required: true
    name: CEPH_SECRET_KEY

  - description: namespace to be watching
    displayName: Middletier Namespace
    required: true
    name: THOTH_MIDDLETIER_NAMESPACE

objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      labels:
        app: thoth
        component: osiris-api
      name: thoth
    data:
      ceph-bucket-name: DH-DEV-DATA
      ceph-bucket-prefix: data/thoth
      ceph-key-id: ${CEPH_KEY_ID}
      ceph-secret-key: ${CEPH_SECRET_KEY}
      storage-bucket-name: thoth-osiris
      ceph-host: https://s3.upshift.redhat.com
      middletier-namespace: ${THOTH_MIDDLETIER_NAMESPACE}
