apiVersion: v1
kind: Template
metadata:
  name: osiris-api-deploymentconfig
  annotations:
    description: >
      This is Osiris API DeploymentConfig Template.
    openshift.io/display-name: 'Thoth: Osiris API'
    version: 0.1.0
    tags: ai-stacks,build-aggregator,build-analysis,thoth,osiris,osiris-api
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris API DeploymentConfig Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-api-deploymentconfig
    app: osiris
    component: osiris-api

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: osiris
        component: osiris-api
      name: osiris-api
    spec:
      replicas: 1
      selector:
        app: osiris
        component: osiris-api
        deploymentconfig: osiris-api
        service: osiris-api
      strategy:
        resources: {}
      template:
        metadata:
          labels:
            app: osiris
            component: osiris-api
            deploymentconfig: osiris-api
            service: osiris-api
        spec:
          serviceAccountName: osiris
          containers:
            - image: osiris-api:latest
              name: osiris-api
              ports:
                - containerPort: 8000
                  protocol: TCP
              resources:
                requests:
                  memory: "384Mi"
                  cpu: "125m"
                limits:
                  memory: "384Mi"
                  cpu: "500m"
              readinessProbe:
                httpGet:
                  path: "/readiness"
                  port: 8000
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                timeoutSeconds: 10
              livenessProbe:
                httpGet:
                  path: "/liveness"
                  port: 8000
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 60
                timeoutSeconds: 10
              env:
                - name: APP_MODULE
                  value: "thoth.osiris.openapi_server:app"
                - name: OSIRIS_API_APP_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: osiris
                      key: app-secret-key
                # - name: SENTRY_DSN
                #   valueFrom:
                #     secretKeyRef:
                #       name: osiris
                #       key: sentry-dsn
                - name: FLASK_ENV
                  value: 'development'
                - name: KUBERNETES_API_URL
                  value: 'https://kubernetes.default.svc.cluster.local'
                - name: KUBERNETES_VERIFY_TLS
                  value: '0'
                - name: MIDDLETIER_NAMESPACE
                  value: 'thoth-test-core'
                - name: THOTH_S3_ENDPOINT_URL
                  valueFrom:
                    configMapKeyRef:
                      key: THOTH_S3_ENDPOINT_URL
                      name: osiris
                - name: THOTH_CEPH_KEY_ID
                  valueFrom:
                    configMapKeyRef:
                      key: THOTH_CEPH_KEY_ID
                      name: osiris
                - name: THOTH_CEPH_SECRET_KEY
                  valueFrom:
                    configMapKeyRef:
                      key: THOTH_CEPH_SECRET_KEY
                      name: osiris
                - name: THOTH_CEPH_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      key: THOTH_CEPH_BUCKET
                      name: osiris
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: THOTH_DEPLOYMENT_NAME
                      name: osiris
                - name: THOTH_CEPH_BUCKET_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      key: THOTH_CEPH_BUCKET_PREFIX
                      name: osiris
            - name: osiris-grpc
              image: osiris-api:latest
              env:
                - name: APP_FILE
                  value: "thoth/osiris/grpc_server.py"
                - name: OSIRIS_API_APP_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: osiris
                      key: app-secret-key
                # - name: SENTRY_DSN
                #   valueFrom:
                #     secretKeyRef:
                #       name: osiris
                #       key: sentry-dsn
              ports:
                - containerPort: 8443
                  protocol: TCP
              resources:
                requests:
                  memory: "384Mi"
                  cpu: "125m"
                limits:
                  memory: "384Mi"
                  cpu: "500m"
              volumeMounts:
                - mountPath: /opt/app-root/src/certs
                  name: osiris-grpc-tls
                  readOnly: true
          volumes:
            - name: osiris-grpc-tls
              secret:
                defaultMode: 420
                secretName: osiris-grpc
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - osiris-api
              - osiris-grpc
            automatic: true
            from:
              kind: ImageStreamTag
              name: osiris-api:latest

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: osiris
        component: openapi
      name: osiris-openapi
    spec:
      ports:
        - name: http
          port: 8000
          protocol: TCP
          targetPort: 8000
      selector:
        service: osiris-api

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: osiris
        component: grpc
      name: osiris-grpc
    spec:
      type: ClusterIP
      ports:
        - name: grpc
          port: 8443
          protocol: TCP
          targetPort: 8443
      selector:
        service: osiris-api

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: osiris-api
      labels:
        app: osiris
        component: osiris-api
    spec:
      port:
        targetPort: http
      to:
        kind: Service
        name: osiris-api

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: osiris
        component: grpc
      name: osiris-grpc
    spec:
      port:
        targetPort: grpc
      tls:
        termination: passthrough
      to:
        kind: Service
        name: osiris-grpc
        weight: 100
      wildcardPolicy: None
