apiVersion: v1
kind: Template
metadata:
  name: osiris-api-deployment
  annotations:
    description: >
      This is Osiris API Secret Template.
    openshift.io/display-name: Thoth:Osiris API
    version: 0.1.0
    tags: ai-stacks,build-aggregator,build-analysis,thoth,osiris,osiris-api
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Osiris API DeploymentConfig Template.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: osiris-api-secrets
    app: thoth
    component: osiris-api

parameters:
  - displayName: App secret key
    description: >
      Secret key for flask application to have secured session connections.
    required: true
    name: OSIRIS_API_APP_SECRET_KEY

  - displayName: SENTRY_DSN
    description: A DSN to a Sentry instance to log to.
    name: SENTRY_DSN
    required: false

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: thoth
      labels:
        app: thoth
        component: osiris-api
    stringData:
      app-secret-key: ${OSIRIS_API_APP_SECRET_KEY}
      sentry-dsn: ${SENTRY_DSN}

  - kind: Secret
    apiVersion: v1
    metadata:
      name: osiris-grpc
    type: kubernetes.io/tls
    data:
      tls.crt: >-
        test
      tls.key: >-
        test
