---
- name: Playbook to deprovision Thoth Osiris Api deployment
  connection: local
  gather_facts: false
  hosts: localhost
  tags:
    - openshift
    - thoth
    - osiris-api
    - osiris

  vars:
    APPLICATION_NAMESPACE: "{{ lookup('env','APPLICATION_NAMESPACE') }}"
    OPENSHIFT_AUTH_TOKEN: "{{ lookup('env','OCP_TOKEN') }}"
    OPENSHIFT_MASTER_URL: "{{ lookup('env','OCP_URL') }}"

  tasks:
    - name: "Login to OpenShift using provided token"
      changed_when: false
      command: >
        oc login {{ OCP_URL }} --insecure-skip-tls-verify=true
         --token {{ OCP_TOKEN }}

    - name: "Deprovision Osiris"
      command: >
        oc --namespace {{ APPLICATION_NAMESPACE }} 
        delete all --selector 'component=osiris-api'
